name: uzo_flutter
description: The official Flutter SDK for Uzo - Africa's location intelligence OS.
version: 1.0.0
homepage: https://uzo.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
